trigger:
  branches:
    include:
      - main

# Use the self-hosted agent pool for Windows
pool:
  name: SelfHostedPool # Replace with your actual pool name

variables:
  - group: azure-vars

steps:
- checkout: self

# Install Terraform on Windows using PowerShell
- powershell: |
    Invoke-WebRequest -Uri https://releases.hashicorp.com/terraform/1.5.0/terraform_1.5.0_windows_amd64.zip -OutFile terraform.zip
    Expand-Archive -Path terraform.zip -DestinationPath $Env:SystemDrive\terraform
    [System.Environment]::SetEnvironmentVariable('PATH', $Env:SystemDrive + '\terraform;' + $Env:PATH, [System.EnvironmentVariableTarget]::Machine)
    terraform --version
  displayName: 'Install Terraform'

# Terraform Init without backend
- powershell: |
    terraform init
  displayName: 'Terraform Init'

# Terraform Plan
- powershell: |
    terraform plan -out=tfplan
  displayName: 'Terraform Plan'

# Terraform Apply
- powershell: |
    terraform apply tfplan
  displayName: 'Terraform Apply'
  env:
    ARM_CLIENT_ID: $(ARM_CLIENT_ID)
    ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
    ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
    ARM_TENANT_ID: $(ARM_TENANT_ID)
