trigger:
  branches:
    include:
      - main

# Use the self-hosted agent pool for Windows
pool:
  name: SelfHostedPool # Replace with your actual pool name

variables:
  - group: azure-vars

steps:
- checkout: self

# Install Terraform on Windows using PowerShell (Skip if already installed)
- powershell: |
    $terraformVersion = "1.5.0"
    $terraformPath = "$Env:SystemDrive\terraform\terraform.exe"
    
    if (Test-Path $terraformPath) {
        $installedVersion = (& $terraformPath --version).Split("`n")[0] -replace "Terraform v", ""
        if ($installedVersion -eq $terraformVersion) {
            Write-Host "Terraform $terraformVersion is already installed. Skipping installation."
        } else {
            Write-Host "Different version of Terraform detected. Installing version $terraformVersion."
            Remove-Item $terraformPath
            Install-Terraform
        }
    } else {
        Write-Host "Terraform not found. Installing version $terraformVersion."
        Install-Terraform
    }

    function Install-Terraform {
        Invoke-WebRequest -Uri "https://releases.hashicorp.com/terraform/$terraformVersion/terraform_${terraformVersion}_windows_amd64.zip" -OutFile terraform.zip
        Expand-Archive -Path terraform.zip -DestinationPath $Env:SystemDrive\terraform
        [System.Environment]::SetEnvironmentVariable('PATH', $Env:SystemDrive + '\terraform;' + $Env:PATH, [System.EnvironmentVariableTarget]::Machine)
        Write-Host "Terraform $terraformVersion installed."
    }

    terraform --version
  displayName: 'Install Terraform (if needed)'

# Terraform Init without backend
- powershell: |
    terraform init
  displayName: 'Terraform Init'

# Terraform Plan
- powershell: |
    terraform plan -out=tfplan
  displayName: 'Terraform Plan'

# Terraform Apply
- powershell: |
    terraform apply tfplan
  displayName: 'Terraform Apply'
  env:
    ARM_CLIENT_ID: $(ARM_CLIENT_ID)
    ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
    ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
    ARM_TENANT_ID: $(ARM_TENANT_ID)
